#!/usr/bin/env php
<?php
// loaders array
$loaders = [
    'vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
];
// find vendor if exists
foreach ($loaders as $file) {
    if (file_exists($file)) {
        require($file);
        $vendor = pathinfo($file, PATHINFO_DIRNAME);
    }
}

// use the luya boot wrapping class
$boot = new \luya\Boot();
$boot->setBaseYiiFile(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
$boot->setConfigArray(['id' => 'gmf', 'basePath' => dirname(__DIR__), 'controllerMap' => [
    'fix' => 'gmf\FixController',
]]);
$boot->run();